#!/bin/bash
# Verification script - Lists all deliverable files

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         API Change Evaluation - Deliverable Verification          ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

WORKSPACE_DIR="$(pwd)"
MISSING_FILES=0
TOTAL_FILES=0

check_file() {
    local filepath=$1
    local description=$2
    TOTAL_FILES=$((TOTAL_FILES+1))
    
    if [ -f "$filepath" ] || [ -d "$filepath" ]; then
        echo "✓ $(printf '%-60s' "$description") $(printf '%-30s' "$filepath")"
    else
        echo "✗ $(printf '%-60s' "$description") $(printf '%-30s' "$filepath")"
        MISSING_FILES=$((MISSING_FILES+1))
    fi
}

echo "ROOT LEVEL FILES & DIRECTORIES"
echo "──────────────────────────────────────────────────────────────────────"
check_file "README.md" "Main documentation"
check_file "QUICK_START.md" "Quick reference guide"
check_file "DELIVERABLES.md" "Deliverables summary"
check_file "INDEX.md" "Navigation index"
check_file "test_data.json" "Canonical test data (6 cases)"
check_file "run_all.sh" "Master test orchestrator"
check_file ".gitignore" "Git exclusions"

echo ""
echo "PROJECT A - PRE-CHANGE (v1 API)"
echo "──────────────────────────────────────────────────────────────────────"
check_file "Project_A_PreChange" "Project A directory"
check_file "Project_A_PreChange/README.md" "Project A documentation"
check_file "Project_A_PreChange/requirements.txt" "Python dependencies"
check_file "Project_A_PreChange/setup.sh" "Environment setup"
check_file "Project_A_PreChange/run_tests.sh" "Test runner"
check_file "Project_A_PreChange/.gitignore" "Git exclusions"

echo ""
echo "PROJECT A - SOURCE CODE"
echo "──────────────────────────────────────────────────────────────────────"
check_file "Project_A_PreChange/src" "Source directory"
check_file "Project_A_PreChange/src/cart_service_v1.py" "v1 service implementation"
check_file "Project_A_PreChange/mocks" "Mock API directory"
check_file "Project_A_PreChange/mocks/mock_api_v1.py" "Mock v1 API server"
check_file "Project_A_PreChange/tests" "Test suite directory"
check_file "Project_A_PreChange/tests/test_pre_change.py" "v1 test suite"
check_file "Project_A_PreChange/data" "Test data directory"
check_file "Project_A_PreChange/logs" "Logs directory (will be generated)"
check_file "Project_A_PreChange/results" "Results directory (will be generated)"

echo ""
echo "PROJECT B - POST-CHANGE (v2 API)"
echo "──────────────────────────────────────────────────────────────────────"
check_file "Project_B_PostChange" "Project B directory"
check_file "Project_B_PostChange/README.md" "Project B documentation"
check_file "Project_B_PostChange/requirements.txt" "Python dependencies"
check_file "Project_B_PostChange/setup.sh" "Environment setup"
check_file "Project_B_PostChange/run_tests.sh" "Test runner"
check_file "Project_B_PostChange/.gitignore" "Git exclusions"

echo ""
echo "PROJECT B - SOURCE CODE"
echo "──────────────────────────────────────────────────────────────────────"
check_file "Project_B_PostChange/src" "Source directory"
check_file "Project_B_PostChange/src/cart_service_v2.py" "v2 service implementation"
check_file "Project_B_PostChange/mocks" "Mock API directory"
check_file "Project_B_PostChange/mocks/mock_api_v2.py" "Mock v2 API with async"
check_file "Project_B_PostChange/tests" "Test suite directory"
check_file "Project_B_PostChange/tests/test_post_change.py" "v2 test suite"
check_file "Project_B_PostChange/data" "Test data directory"
check_file "Project_B_PostChange/logs" "Logs directory (will be generated)"
check_file "Project_B_PostChange/results" "Results directory (will be generated)"

echo ""
echo "SHARED RESULTS DIRECTORY (generated after run_all.sh)"
echo "──────────────────────────────────────────────────────────────────────"
check_file "results" "Aggregated results directory"
echo "  (Note: files below will be generated by run_all.sh)"
echo "  - compare_report.md"
echo "  - results_pre.json"
echo "  - results_post.json"
echo "  - aggregated_metrics.json"

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "SUMMARY"
echo "════════════════════════════════════════════════════════════════════════"
echo "Total files checked: $TOTAL_FILES"
echo "Missing files: $MISSING_FILES"

if [ $MISSING_FILES -eq 0 ]; then
    echo ""
    echo "✓ ALL DELIVERABLES PRESENT AND READY"
    echo ""
    echo "Next steps:"
    echo "  1. bash run_all.sh              # Execute complete evaluation"
    echo "  2. cat results/compare_report.md # Review findings"
    exit 0
else
    echo ""
    echo "✗ SOME DELIVERABLES MISSING"
    echo "Please verify the project structure"
    exit 1
fi
